In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv"

df = pd.read_csv(url)
df.head(10)

   id                      name    place  year    lat   long      lat_long
0   0        Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1        Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2        Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3        Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4        Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57
5   5        Bapaume, Robert de  England  1516  51.51  -0.12  51.51, -0.12
6   6  Passano, Jean-Joachim de  England  1527  51.51  -0.12  51.51, -0.12
7   7               De Monpreat  England  1532  51.51  -0.12  51.51, -0.12
8   8           Du Bellay, Jean  England  1530  51.51  -0.12  51.51, -0.12
9   9     Castelnau, Antoine de  England  1534  51.51  -0.12  51.51, -0.12

In [5]:
# File paths
# absolute paths
# starts at the root of the computer
    # /user/<user-name>/otherfile/otherfile
# relative path
    #starts at the folder we are currently in
    # use . notation to determine location
    # go back = ../
    # go back two folders = ../../foldername/file.csv
    # current folder = ./

In [ ]:
# write our df to the data folder.
# df.to_csv("./data/french-ambs.csv", index=False)

In [9]:
# read csv to df
df = pd.read_csv("./data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [10]:
#iloc[] uses index number and columns number
df.iloc[10]

id                      10
name        De Selve, Odet
place              England
year                  1547
lat                  51.51
long                 -0.12
lat_long      51.51, -0.12
Name: 10, dtype: object

In [11]:
df.iloc[100:110]

,id,name,place,year,lat,long,lat_long
100,100,"Bellièvre, Pomponne de",Swiss Cantons,1570,46.94,7.45,"46.94, 7.45"
101,101,"Bellièvre, Jean de, sr. de Hautefort",Swiss Cantons,1579,46.94,7.45,"46.94, 7.45"
102,102,"Vigier, Jean",Swiss Cantons,1581,46.94,7.45,"46.94, 7.45"
103,103,"De Pins, Jean",Venice,1517,45.44,12.33,"45.44, 12.33"
104,104,"De Pins, Jean",Venice,1518,45.44,12.33,"45.44, 12.33"
105,105,"Du Gabre, Dominique",Venice,1554,45.44,12.33,"45.44, 12.33"
106,106,"Carmain, Paul de",Venice,1569,45.44,12.33,"45.44, 12.33"
107,107,"Du Ferrier, Arnaud",Venice,1576,45.44,12.33,"45.44, 12.33"
108,108,"De Selve, Odet",Venice,1551,45.44,12.33,"45.44, 12.33"
109,109,"Hurault, André",Venice,1583,45.44,12.33,"45.44, 12.33"

In [12]:
df.iloc[0,3]

np.int64(1543)

In [13]:
# at.[] .iat[] get only cells
df.at[0, "place"]

'Denmark'

In [14]:
df.iat[0,2]

'Denmark'

In [21]:
# rename with an iteration:
#  iterrows and intertuples
# iterrows
for idx, item in df.iterrows():
    print(item["place"])

Denmark
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Portugal
Rome
Portugal
Rome
Rome
Rome
Rome
Savoy
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Venice
Denmark
England
England
England
England
England
England
England
Grisons
England
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
Denmark
England
England
Denmark
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Savoy
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Ferrara
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Rome
Rome
Scotland
Scotland
Spain
Venice
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
Ferrara
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Spain
Spain
Scotland
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Poland
Poland
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Ferrara
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Rome
Rome
Rome
Rome
Rome
Savoy
Saxony
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Tuscany
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Venice
Denmark
Denmark
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Savoy
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Swiss Cantons
Venice
Venice
Holy Roman Empire

In [25]:
# itertuples
for item in df.itertuples():
    print(item.place)

Denmark
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Portugal
Rome
Portugal
Rome
Rome
Rome
Rome
Savoy
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Venice
Denmark
England
England
England
England
England
England
England
Grisons
England
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
Denmark
England
England
Denmark
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Savoy
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Ferrara
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Rome
Rome
Scotland
Scotland
Spain
Venice
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
Ferrara
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Spain
Spain
Scotland
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Poland
Poland
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Ferrara
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Rome
Rome
Rome
Rome
Rome
Savoy
Saxony
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Tuscany
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Venice
Denmark
Denmark
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Savoy
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Swiss Cantons
Venice
Venice
Holy Roman Empire

In [27]:
for idx, id, n, p, y, lt, lg, _ in df.itertuples():
    print(p)

Denmark
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Portugal
Rome
Portugal
Rome
Rome
Rome
Rome
Savoy
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Venice
Denmark
England
England
England
England
England
England
England
Grisons
England
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
Denmark
Denmark
England
England
Denmark
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Savoy
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Ferrara
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Rome
Rome
Scotland
Scotland
Spain
Venice
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
Ferrara
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Spain
Spain
Scotland
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
Denmark
Denmark
England
England
England
England
England
Grisons
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Poland
Poland
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Denmark
Denmark
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Ferrara
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Portugal
Rome
Rome
Rome
Rome
Rome
Savoy
Saxony
Rome
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Tuscany
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Rome
Rome
Rome
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Scotland
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Tuscany
Venice
Denmark
Denmark
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Holy Roman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Savoy
Scotland
Scotland
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Rome
Denmark
Denmark
Denmark
England
England
England
England
England
England
England
Grisons
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Portugal
Portugal
Portugal
Portugal
Rome
Rome
Rome
Rome
Saxony
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Venice
Venice
Venice
Rome
England
England
England
England
England
Geneva
Grisons
Grisons
Grisons
Grisons
Holy Roman Empire
Holy Roman Empire
Holy Roman Empire
Netherlands
Netherlands
Netherlands
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Ottoman Empire
Poland
Ottoman Empire
Portugal
Rome
Rome
Rome
Rome
Rome
Rome
Rome
Scotland
Scotland
Spain
Spain
Spain
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Swiss Cantons
Venice
Venice
Venice
Venice
Swiss Cantons
Venice
Venice
Holy Roman Empire

In [28]:
# rename Denmark with itertuples:
for item in df.itertuples():
    if item.place == 'Denmark':
        df.at[item.Index, "place"] = "Den."
df["place"].unique()

array(['Den.', 'England', 'Geneva', 'Grisons', 'Holy Roman Empire',
       'Netherlands', 'Ottoman Empire', 'Portugal', 'Rome', 'Scotland',
       'Spain', 'Swiss Cantons', 'Venice', 'Poland', 'Savoy', 'Ferrara',
       'Saxony', 'Tuscany'], dtype=object)

In [33]:
# df.loc[] to rename only one variable name
df.loc[df["place"] == 'England', "place"] = "Eng."
df["place"].unique()

array(['Den.', 'Eng.', 'Geneva', 'Grisons', 'Holy Roman Empire',
       'Netherlands', 'Ottoman Empire', 'Portugal', 'Rome', 'Scotland',
       'Spain', 'Swiss Cantons', 'Venice', 'Poland', 'Savoy', 'Ferrara',
       'Saxony', 'Tuscany'], dtype=object)

In [37]:
# # hash = {
#     "Geneva": "Gen",
#     "Grisons": "Gri.",
# }

hash = {
    place:f"{place[:3]}." for place in df["place"].unique()
    }
df['place'] = df["place"].replace(hash)
df["place"].unique()

array(['Den.', 'Eng.', 'Gen.', 'Gri.', 'Hol.', 'Net.', 'Ott.', 'Por.',
       'Rom.', 'Sco.', 'Spa.', 'Swi.', 'Ven.', 'Pol.', 'Sav.', 'Fer.',
       'Sax.', 'Tus.'], dtype=object)

In [38]:
df.head()

   id                name place  year    lat   long      lat_long
0   0  Richer, Christophe  Den.  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Den.  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Den.  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Den.  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Den.  1582  55.68  12.57  55.68, 12.57

In [40]:
df.loc[(df["place"] == "Eng.") & (df["year"] >= 1550) & (df["year"] <= 1555)]. count ()

id          8
name        8
place       8
year        8
lat         8
long        8
lat_long    8
dtype: int64

In [41]:
df.loc[~(df["place"] == "Eng.") & (df["year"] >= 1550) & (df["year"] <= 1555)]. count ()

id          61
name        61
place       61
year        61
lat         61
long        61
lat_long    61
dtype: int64

In [44]:
imp_emb = ["Ven.", "Eng.", "Ott."]

imp_num = df.loc[(df["place"].isin(imp_emb)) & (df["year"] >= 1550) & (df["year"] <= 1555)]. count ()
non_imp_num = df.loc[~(df["place"].isin(imp_emb)) & (df["year"] >= 1550) & (df["year"] <= 1555)]. count ()
all_num = df.loc [(df["year"] >= 1550) & (df["year"] <= 1555)].count()

print(f"all ambs: {all_num}")
print(f"% to imp: {imp_num / all_num}")
print(f"% to non_imp: {non_imp_num / all_num}")

all ambs: id          69
name        69
place       69
year        69
lat         69
long        69
lat_long    69
dtype: int64
% to imp: id          0.376812
name        0.376812
place       0.376812
year        0.376812
lat         0.376812
long        0.376812
lat_long    0.376812
dtype: float64
% to non_imp: id          0.623188
name        0.623188
place       0.623188
year        0.623188
lat         0.623188
long        0.623188
lat_long    0.623188
dtype: float64