- Pandas?
- Series?
- DataFrame?
- create df
- create/update columns
- vectorized operations
- change values
- .loc => filtering

In [55]:
from typing import List
import pandas as pd

example_list: list[int] = [1, 2, 3, 4, 5]
type (example_list)

list

In [56]:
example_list.pop()

5

In [57]:
example_list

[1, 2, 3, 4]

In [58]:
s1 = pd.Series(example_list)
s1.index = ["A", "B", "C", "D"]

In [59]:
s1 ["A"] = 23

In [60]:
s1

A    23
B     2
C     3
D     4
dtype: int64

In [61]:
s1.index = range(4)
s1

0    23
1     2
2     3
3     4
dtype: int64

In [62]:
# Create a df from dictionary
names = ["Nate", "Rebecca", "Edwin", "Preston"]
age = [39, 40, 11, 7]
year = ["senior", "junior", "sophomore", "freshman"]

students = {
    "name": names,
    "age": age,
    "year": year
}
students_df = pd.DataFrame(students)
students_df

      name  age       year
0     Nate   39     senior
1  Rebecca   40     junior
2    Edwin   11  sophomore
3  Preston    7   freshman

In [63]:
import random
# Create df from a list of rows

players = ["Messi", "Mbappe", "Ronaldo", "Sala"]

cols = ["name", "goals/game", "games"]
data = [ 
        [player, random.random(), round(random.random() * 1000)]
        for player in players
        ]
players_df = pd.DataFrame(data=data, columns=cols)
players_df

      name  goals/game  games
0    Messi    0.672626    614
1   Mbappe    0.568723    434
2  Ronaldo    0.469571    223
3     Sala    0.090578    449

In [64]:
# create/update columns
players_df["name"]

0      Messi
1     Mbappe
2    Ronaldo
3       Sala
Name: name, dtype: object

In [65]:
players_df["name"][0]

'Messi'

In [66]:
players_df["new_col"] = 0
players_df

      name  goals/game  games  new_col
0    Messi    0.672626    614        0
1   Mbappe    0.568723    434        0
2  Ronaldo    0.469571    223        0
3     Sala    0.090578    449        0

In [67]:
players_df["new_col"] = [i+1 for i in range(len(players_df))]
players_df

      name  goals/game  games  new_col
0    Messi    0.672626    614        1
1   Mbappe    0.568723    434        2
2  Ronaldo    0.469571    223        3
3     Sala    0.090578    449        4

In [68]:
len(players_df)

4

In [69]:
players_df["new_col"] = players_df["goals/game"] * players_df["games"]
players_df

      name  goals/game  games     new_col
0    Messi    0.672626    614  412.992376
1   Mbappe    0.568723    434  246.825991
2  Ronaldo    0.469571    223  104.714340
3     Sala    0.090578    449   40.669692

In [70]:
# inline vs declaritive
# players_df.rename(columns={"new_col": "goals"}, inplace=True)
players_df = players_df.rename(columns={"new_col": "goals"})
players_df

      name  goals/game  games       goals
0    Messi    0.672626    614  412.992376
1   Mbappe    0.568723    434  246.825991
2  Ronaldo    0.469571    223  104.714340
3     Sala    0.090578    449   40.669692

In [71]:
players_df["name"] = players_df["name"].str.lower()
players_df

      name  goals/game  games       goals
0    messi    0.672626    614  412.992376
1   mbappe    0.568723    434  246.825991
2  ronaldo    0.469571    223  104.714340
3     sala    0.090578    449   40.669692

In [72]:
players_df[["name", "goals"]]

      name       goals
0    messi  412.992376
1   mbappe  246.825991
2  ronaldo  104.714340
3     sala   40.669692

In [73]:
# .loc[]

players_df = players_df.set_index("name")
players_df

         goals/game  games       goals
name
messi      0.672626    614  412.992376
mbappe     0.568723    434  246.825991
ronaldo    0.469571    223  104.714340
sala       0.090578    449   40.669692

In [74]:
players_df.loc["mbappe", "games"]

np.int64(434)

In [75]:
players_df = players_df.reset_index()
players_df

      name  goals/game  games       goals
0    messi    0.672626    614  412.992376
1   mbappe    0.568723    434  246.825991
2  ronaldo    0.469571    223  104.714340
3     sala    0.090578    449   40.669692

In [76]:
players_df.loc[0]

name               messi
goals/game      0.672626
games                614
goals         412.992376
Name: 0, dtype: object

In [78]:
players_df.loc[1:2, "games":"goals"]

   games       goals
1    434  246.825991
2    223  104.714340

In [79]:
players_df.loc[[0,3,2]]

      name  goals/game  games       goals
0    messi    0.672626    614  412.992376
3     sala    0.090578    449   40.669692
2  ronaldo    0.469571    223  104.714340

In [80]:
players_df.loc[players_df["goals/game"]>0.5]

     name  goals/game  games       goals
0   messi    0.672626    614  412.992376
1  mbappe    0.568723    434  246.825991

In [81]:
players_df.loc[players_df["goals/game"]>0.5, "name"]

0     messi
1    mbappe
Name: name, dtype: object

In [82]:
players_df.loc[players_df["goals/game"]>0.5, "name"] = "MBAPPE"

In [83]:
players_df

      name  goals/game  games       goals
0   MBAPPE    0.672626    614  412.992376
1   MBAPPE    0.568723    434  246.825991
2  ronaldo    0.469571    223  104.714340
3     sala    0.090578    449   40.669692

In [84]:
players_df['team'] = ["FC Barca", "PSG", "PSG", "Liverpool"]
players_df

      name  goals/game  games       goals       team
0   MBAPPE    0.672626    614  412.992376   FC Barca
1   MBAPPE    0.568723    434  246.825991        PSG
2  ronaldo    0.469571    223  104.714340        PSG
3     sala    0.090578    449   40.669692  Liverpool

In [88]:
players_df.loc[players_df["team"] == "PSG", "team"] = "Paris St. Germain"
players_df

      name  goals/game  games       goals               team
0   MBAPPE    0.672626    614  412.992376           FC Barca
1   MBAPPE    0.568723    434  246.825991  Paris St. Germain
2  ronaldo    0.469571    223  104.714340  Paris St. Germain
3     sala    0.090578    449   40.669692          Liverpool