- apply 
- datetimes
- group
- agg

In [49]:
import pandas as pd
df = pd.read_csv("./data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [50]:
from random import choice
# import random
# random.choice 
df["date_start"] = f"{df["year"]}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}"
df.head()

,id,name,place,year,lat,long,lat_long,date_start
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...

In [51]:
df = df.drop(columns=["date_start","lat_long"])
df = df[["name", "place", "year"]]
df.head()

                 name    place  year
0  Richer, Christophe  Denmark  1543
1  Richer, Christophe  Denmark  1541
2  Danzay, Charles de  Denmark  1561
3  Danzay, Charles de  Denmark  1563
4  Danzay, Charles de  Denmark  1582

In [52]:
# apply on data series
def my_function(x):
    return x

df["date_start"] = df["year"].apply(lambda x: f"{x}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}")
df.head()

                 name    place  year  date_start
0  Richer, Christophe  Denmark  1543  1543-03-04
1  Richer, Christophe  Denmark  1541  1541-04-16
2  Danzay, Charles de  Denmark  1561  1561-11-05
3  Danzay, Charles de  Denmark  1563  1563-04-12
4  Danzay, Charles de  Denmark  1582  1582-09-24

In [53]:
import numpy as np
def get_date_start(row):
    rows = df.loc[
        (df["place"] == row["place"]) &
        (df["name"] == row["name"]) &
        (df["year"] == row["year"] - 1)
    ]
    if len(rows) > 0: # len(rows) > 0
        return np.nan
        
    date_string = f"{row['year']}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}"
    return date_string

df["date_start"] = df.apply(get_date_start, axis=1)
df.head()

                 name    place  year  date_start
0  Richer, Christophe  Denmark  1543         NaN
1  Richer, Christophe  Denmark  1541  1541-02-09
2  Danzay, Charles de  Denmark  1561         NaN
3  Danzay, Charles de  Denmark  1563         NaN
4  Danzay, Charles de  Denmark  1582         NaN

In [54]:
def get_date_end(row):
    rows = df.loc[
        (df["place"] == row["place"]) &
        (df["name"] == row["name"]) &
        (df["year"] == row["year"] + 1)
    ]
    if len(rows) > 0: # len(rows) > 0
        return np.nan
        
    date_string = f"{row['year']}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}"
    return date_string

df["date_end"] = df.apply(get_date_end, axis=1)
df.head()

                 name    place  year  date_start date_end
0  Richer, Christophe  Denmark  1543         NaN      NaN
1  Richer, Christophe  Denmark  1541  1541-02-09      NaN
2  Danzay, Charles de  Denmark  1561         NaN      NaN
3  Danzay, Charles de  Denmark  1563         NaN      NaN
4  Danzay, Charles de  Denmark  1582         NaN      NaN

In [55]:
# bfill(), ffill() but first sort values appropiately
df = df.sort_values(["place", "name", "year"], ascending=True)
df

                    name    place  year  date_start    date_end
422   Danzay, Charles de  Denmark  1557  1557-05-03         NaN
638   Danzay, Charles de  Denmark  1558         NaN         NaN
704   Danzay, Charles de  Denmark  1559         NaN         NaN
421   Danzay, Charles de  Denmark  1560         NaN         NaN
2     Danzay, Charles de  Denmark  1561         NaN         NaN
..                   ...      ...   ...         ...         ...
112     Séguier, Antoine   Venice  1599         NaN         NaN
531     Séguier, Antoine   Venice  1600         NaN  1600-09-01
353  d'Armagnac, Georges   Venice  1536  1536-09-18         NaN
756  d'Armagnac, Georges   Venice  1537         NaN         NaN
757  d'Armagnac, Georges   Venice  1538         NaN  1538-03-09

[869 rows x 5 columns]

In [ ]:
from datetime import datetime
fmt = "%Y-%m-%d"

df["date_end"] = df["date_end"]. apply(lambda x: datetime.strptime(x, fmt))
df["date_start"] = df["date_start"]. apply(lambda x: datetime.strptime(x, fmt))

TypeError: strptime() argument 1 must be str, not float

In [57]:
placesdf = df.groupby(["place"]).count()

In [64]:
placesdf = df.groupby(["place"]).agg(
    {
        "name": "count",
        "year": ["min", "max"],
    }
).reset_index()
placesdf

                place  name  year
                      count   min   max
0             Denmark    40  1541  1589
1             England    93  1516  1600
2             Ferrara     3  1535  1554
3              Geneva     2  1559  1560
4             Grisons    77  1525  1588
5   Holy Roman Empire    81  1519  1600
6         Netherlands    45  1529  1600
7      Ottoman Empire    89  1535  1600
8              Poland     7  1572  1574
9            Portugal    56  1522  1578
10               Rome    82  1513  1589
11              Savoy     4  1528  1574
12             Saxony     3  1570  1572
13           Scotland    22  1548  1588
14              Spain    35  1559  1589
15      Swiss Cantons   131  1522  1600
16            Tuscany     3  1527  1529
17             Venice    96  1516  1600

In [61]:
placesdf = df.groupby("place").agg(
    num=("year", "count"),
    min_year=("year", "min"),
    max_year=("year", "max"),
    ambs=("name", "unique"),
    num_ambs=("name", "nunique"),
).sort_values(["num"]).reset_index()
placesdf

,place,num,min_year,max_year,ambs,num_ambs
0,Denmark,40,1541,1589,"[Danzay, Charles de, Richer, Christophe]",2
1,England,93,1516,1600,"[Bapaume, Robert de, Bochetel, Jacques, Castel...",26
2,Ferrara,3,1535,1554,"[Du Gabre, Dominique, Langeac, Jean de]",2
3,Geneva,2,1559,1560,"[Boistaillé, Jean Hurault de]",1
4,Grisons,77,1525,1588,"[Bellièvre, Pomponne de, Cambray, Jean-Jacques...",13
5,Holy Roman Empire,81,1519,1600,"[Ancel, Guillaume, Bochetel, Bernardin, Calvim...",15
6,Netherlands,45,1529,1600,"[Blatier, Claude, Bochetel, Jacques, Choary, P...",12
7,Ottoman Empire,89,1535,1600,"[Berthier, Sébastien, Cambray, Jacques de, Cot...",20
8,Poland,7,1572,1574,"[Fayes, Jacques, sr d'Espesses, Lansac, Guy de...",5
9,Portugal,56,1522,1578,"[De Caix, Honoré, De Seurre, Miguel, Nicot, Je...",5
10,Rome,82,1513,1589,"[Adhemar, Louis, Babou, Philibert, Carmain, Pa...",24
11,Savoy,4,1528,1574,"[Des Barres, Louis, Henri d'Angouleme, Sr. de ...",3
12,Saxony,3,1570,1572,"[Schomberg, Gaspard de]",1
13,Scotland,22,1548,1588,"[Clutin, Henri, Courcelles, Baron de, Du Croc,...",4
14,Spain,35,1559,1589,"[Fourquevaux, Raymond de Beccarie de Pavie, Ba...",5
15,Swiss Cantons,131,1522,1600,"[Bellièvre, Jean de, sr. de Hautefort, Bellièv...",27
16,Tuscany,3,1527,1529,"[Dodieu, Claude]",1
17,Venice,96,1516,1600,"[Boistaillé, Jean Hurault de, Canossa, Louis d...",20

In [63]:
place_names = df.groupby("place").agg(
    num=("year", "count"),
    min_year=("year", "min"),
    max_year=("year", "max"),
    ambs=("name", "unique"),
    num_ambs=("name", "nunique"),
).reset_index().sort_values(["num"])
place_names

,place,num,min_year,max_year,ambs,num_ambs
3,Geneva,2,1559,1560,"[Boistaillé, Jean Hurault de]",1
2,Ferrara,3,1535,1554,"[Du Gabre, Dominique, Langeac, Jean de]",2
12,Saxony,3,1570,1572,"[Schomberg, Gaspard de]",1
16,Tuscany,3,1527,1529,"[Dodieu, Claude]",1
11,Savoy,4,1528,1574,"[Des Barres, Louis, Henri d'Angouleme, Sr. de ...",3
8,Poland,7,1572,1574,"[Fayes, Jacques, sr d'Espesses, Lansac, Guy de...",5
13,Scotland,22,1548,1588,"[Clutin, Henri, Courcelles, Baron de, Du Croc,...",4
14,Spain,35,1559,1589,"[Fourquevaux, Raymond de Beccarie de Pavie, Ba...",5
0,Denmark,40,1541,1589,"[Danzay, Charles de, Richer, Christophe]",2
6,Netherlands,45,1529,1600,"[Blatier, Claude, Bochetel, Jacques, Choary, P...",12
9,Portugal,56,1522,1578,"[De Caix, Honoré, De Seurre, Miguel, Nicot, Je...",5
4,Grisons,77,1525,1588,"[Bellièvre, Pomponne de, Cambray, Jean-Jacques...",13
5,Holy Roman Empire,81,1519,1600,"[Ancel, Guillaume, Bochetel, Bernardin, Calvim...",15
10,Rome,82,1513,1589,"[Adhemar, Louis, Babou, Philibert, Carmain, Pa...",24
7,Ottoman Empire,89,1535,1600,"[Berthier, Sébastien, Cambray, Jacques de, Cot...",20
1,England,93,1516,1600,"[Bapaume, Robert de, Bochetel, Jacques, Castel...",26
17,Venice,96,1516,1600,"[Boistaillé, Jean Hurault de, Canossa, Louis d...",20
15,Swiss Cantons,131,1522,1600,"[Bellièvre, Jean de, sr. de Hautefort, Bellièv...",27